---
- name: vim | install neovim support via rubygems
  gem: name=neovim user_install=yes

- name: vim | install neovim support via pip2
  pip: executable=pip2 name=neovim

- name: vim | install neovim support via pip3
  pip: executable=pip3 name=neovim

# Optional really; just allows us to release updates to deoplete sorter
# extension dependency (commandt.score).
- name: vim | install twine via pip3
  pip: executable=pip3 name=twine

- name: vim | install commandt.score via pip3
  pip: executable=pip3 name=commandt.score
